name: Minecraft AFK Bot

on:
  schedule:
    - cron: '0 */5 * * *'

  workflow_dispatch:

jobs:
  run-bot:
    name: Run AFK Bot
    runs-on: ubuntu-latest
    timeout-minutes: 290

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Start AFK Bot
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
          MC_VERSION: ${{ secrets.MC_VERSION }}
        run: node bot.js
